---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: kubesec-webhook
  labels:
    app: kubesec-webhook
    kind: validator
webhooks:
  - name: deployment.admission.kubesc.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZENFVWQ1FmUG1wQ3N4WXAxUXM5MG52b3FPNGVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJ0MVltVnpaV010ZDJWaWFHOXZheTVyZFdKbGMyVmpMbk4yWXpBZUZ3MHhPREE1TWpVeQpNalEyTXpaYUZ3MHhPVEE1TWpVeU1qUTJNelphTUNZeEpEQWlCZ05WQkFNTUcydDFZbVZ6WldNdGQyVmlhRzl2CmF5NXJkV0psYzJWakxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNd3AKUTJ2bjVaemtieUNtWVdSakM1K3NKUzVvTUp4U3FBS09wNDdvVTVva1JjV011azNEaVViYU1CUDJMeWJQdnlsNQp5ajEzaHIrKzRkRFk2cnFEdjJpRG5VeTFpZVkxUVNvZG14SHU5WmVlV1l0cDJMb2hiempVUU1QSWUxb0NYYXZMCmxVendpUEFaaUdDU3VuZUVBOUI3dXR5QVpmRlRkd3VxWXJram9ja2hZMllZNTJEa3dZazFoUVNPRFdyMU42dGMKc2xOMjNIY0hTUkNNNnMzRE9XU0dsb2srRTFGQ2xyUm82MXpmaGhwL20zTVF1UTk4bzQ1WnRiSVFLY01tQmphNgpsQUR2NmxsRkJ0akNYVlVyM0FNaEloUWptdEZFQUF0eVFwdGI5NGpPRC9GWk9xdGVNbHFydXFCU05DT2RjV2tUCm5LUjh4SUpETzdLVG9PM3lVN0VDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHMnlPSDl3RFlwL3MKUkhaSTZlZStrVHA2d0NRVWRROUVOTnpEeXVSejYwbXZLdWR1Uk41dDNSRG5iaEpib3pwYXc5c21XT2s3bjJKMwpUTWhnbW94ajRuZ0NiR0ZpTWdkN0Q5SlovNXI2dTlTMWZJVGVBNXVzMDExSWZCQU95YW02czE4blkxZG5aWXZGCmthTUVPM3BiUGdTWllla0dETSt0SE5na09EbVlxQmtsaVF0N2RJa1NQN0xuZmRPWmhMYm5rUlVEdnhPWVZWZkQKb0hseWhQaFZTdlJldUYzRjQyS3BVNlVTNGVUN3F5S0JjSWZ3blJXdWxNRi9NNXd2cHByRzdxelRBcmRRMmszWApPeU9HdGVZbWhXWE1GYmV5eGw1blFkQk1zQm1LN25acGNaZ245dlU5algxeW10cjRkSDFyV0poVEI4ajNiQk90CnJVMlVxbUNLZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - deployments
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
  - name: daemonset.admission.kubesc.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/daemonset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZENFVWQ1FmUG1wQ3N4WXAxUXM5MG52b3FPNGVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJ0MVltVnpaV010ZDJWaWFHOXZheTVyZFdKbGMyVmpMbk4yWXpBZUZ3MHhPREE1TWpVeQpNalEyTXpaYUZ3MHhPVEE1TWpVeU1qUTJNelphTUNZeEpEQWlCZ05WQkFNTUcydDFZbVZ6WldNdGQyVmlhRzl2CmF5NXJkV0psYzJWakxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNd3AKUTJ2bjVaemtieUNtWVdSakM1K3NKUzVvTUp4U3FBS09wNDdvVTVva1JjV011azNEaVViYU1CUDJMeWJQdnlsNQp5ajEzaHIrKzRkRFk2cnFEdjJpRG5VeTFpZVkxUVNvZG14SHU5WmVlV1l0cDJMb2hiempVUU1QSWUxb0NYYXZMCmxVendpUEFaaUdDU3VuZUVBOUI3dXR5QVpmRlRkd3VxWXJram9ja2hZMllZNTJEa3dZazFoUVNPRFdyMU42dGMKc2xOMjNIY0hTUkNNNnMzRE9XU0dsb2srRTFGQ2xyUm82MXpmaGhwL20zTVF1UTk4bzQ1WnRiSVFLY01tQmphNgpsQUR2NmxsRkJ0akNYVlVyM0FNaEloUWptdEZFQUF0eVFwdGI5NGpPRC9GWk9xdGVNbHFydXFCU05DT2RjV2tUCm5LUjh4SUpETzdLVG9PM3lVN0VDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHMnlPSDl3RFlwL3MKUkhaSTZlZStrVHA2d0NRVWRROUVOTnpEeXVSejYwbXZLdWR1Uk41dDNSRG5iaEpib3pwYXc5c21XT2s3bjJKMwpUTWhnbW94ajRuZ0NiR0ZpTWdkN0Q5SlovNXI2dTlTMWZJVGVBNXVzMDExSWZCQU95YW02czE4blkxZG5aWXZGCmthTUVPM3BiUGdTWllla0dETSt0SE5na09EbVlxQmtsaVF0N2RJa1NQN0xuZmRPWmhMYm5rUlVEdnhPWVZWZkQKb0hseWhQaFZTdlJldUYzRjQyS3BVNlVTNGVUN3F5S0JjSWZ3blJXdWxNRi9NNXd2cHByRzdxelRBcmRRMmszWApPeU9HdGVZbWhXWE1GYmV5eGw1blFkQk1zQm1LN25acGNaZ245dlU5algxeW10cjRkSDFyV0poVEI4ajNiQk90CnJVMlVxbUNLZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - daemonsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
  - name: statefulset.admission.kubesc.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/statefulset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZENFVWQ1FmUG1wQ3N4WXAxUXM5MG52b3FPNGVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJ0MVltVnpaV010ZDJWaWFHOXZheTVyZFdKbGMyVmpMbk4yWXpBZUZ3MHhPREE1TWpVeQpNalEyTXpaYUZ3MHhPVEE1TWpVeU1qUTJNelphTUNZeEpEQWlCZ05WQkFNTUcydDFZbVZ6WldNdGQyVmlhRzl2CmF5NXJkV0psYzJWakxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNd3AKUTJ2bjVaemtieUNtWVdSakM1K3NKUzVvTUp4U3FBS09wNDdvVTVva1JjV011azNEaVViYU1CUDJMeWJQdnlsNQp5ajEzaHIrKzRkRFk2cnFEdjJpRG5VeTFpZVkxUVNvZG14SHU5WmVlV1l0cDJMb2hiempVUU1QSWUxb0NYYXZMCmxVendpUEFaaUdDU3VuZUVBOUI3dXR5QVpmRlRkd3VxWXJram9ja2hZMllZNTJEa3dZazFoUVNPRFdyMU42dGMKc2xOMjNIY0hTUkNNNnMzRE9XU0dsb2srRTFGQ2xyUm82MXpmaGhwL20zTVF1UTk4bzQ1WnRiSVFLY01tQmphNgpsQUR2NmxsRkJ0akNYVlVyM0FNaEloUWptdEZFQUF0eVFwdGI5NGpPRC9GWk9xdGVNbHFydXFCU05DT2RjV2tUCm5LUjh4SUpETzdLVG9PM3lVN0VDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHMnlPSDl3RFlwL3MKUkhaSTZlZStrVHA2d0NRVWRROUVOTnpEeXVSejYwbXZLdWR1Uk41dDNSRG5iaEpib3pwYXc5c21XT2s3bjJKMwpUTWhnbW94ajRuZ0NiR0ZpTWdkN0Q5SlovNXI2dTlTMWZJVGVBNXVzMDExSWZCQU95YW02czE4blkxZG5aWXZGCmthTUVPM3BiUGdTWllla0dETSt0SE5na09EbVlxQmtsaVF0N2RJa1NQN0xuZmRPWmhMYm5rUlVEdnhPWVZWZkQKb0hseWhQaFZTdlJldUYzRjQyS3BVNlVTNGVUN3F5S0JjSWZ3blJXdWxNRi9NNXd2cHByRzdxelRBcmRRMmszWApPeU9HdGVZbWhXWE1GYmV5eGw1blFkQk1zQm1LN25acGNaZ245dlU5algxeW10cjRkSDFyV0poVEI4ajNiQk90CnJVMlVxbUNLZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - statefulsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
