---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: in-toto-webhook
  labels:
    app: in-toto-webhook
    kind: validator
webhooks:
  - name: deployment.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZETlNCeXBnKzV0RTZpVFpqcGNjT3VNOGQxaHBNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNekkzTVRkYUZ3MHhPVEV3TVRreE16STNNVGRhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPSjAKa3VscU54d1JpRDJxT1d4WUV5aUVoUVo1TUpOUWc5L0xUSmFaOGNFVlBlUlRtQmVObnAxeXBZWXJ5ZnhIeXVNSwpSY0JPRCtremRTZWIwWmUvcndvVkYwZmd6K3V1RXptMUwzVnR3ajRmMjNsM1I0RE9RR2JnRlRVSVExY2pRNTViCmhCVis1dGJWZnAwSXJYRFZjdHQ2a2lLcWpUN3lhUFFLS2dqdWg2akQ1b3pWUnVCMkFpMndFb28yUUY4VDJINEoKUklGVldObDVBa0dHbDZ3dmZSOHlGVXFSczBBMVExSzl1SHZOS3hQNk5HRit3QkRFLzBOMGhzM3dFZXYrNTdEMQpkZWtKOWJ3emZVOW9LM0gwVjVKMEpuamJvK2ZNeENlL1ArRHc3R3MrUGl2U3pIelhJVjgrbGVDalEyVlY4SlBKCk9NcU91ZlUyVE1FZWVIL0VvdWtDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMRDg5YnN4cXg4MDIKeHVGUlNYOUpLSXMvN3lTZnMrRnRrYVBHUzl3b3FRRmF0cFYyS3U4NVNhY1VwSG4rOVVVNmIwRXh5VDlkdzRabwpUMFJxYU5FaDZlQzIzaC9BZmh5VG5hUDVkU2kvVlVVaXFnNzlCZ0RuV0ppSHIyYkVjbTRJUEpDRE1zQWhzckl0CmRoS25udklSSmpjMCtoSVNWSnNMLzFhRXFaeis5d3AzbXhDSlF6NVVwMkgydUZVK2hDQnVUbXBMcWV6WG9VKzMKQTZEa3ZmVDdkMWZyUG9zRnJqbS9ESDFJU2FobFZleEt2bS80L25RV3p5QkpuUktyREdSVXgvOXgvaXAyY3kwWAppWGZOaVh1b0dpci9weUdyNm9IakRmdUdLby9HbzNYR3FHcEpmekp2bWJJYnJhdi9SZmFxcHliOFZrbjNyVGV0CktNbmM1RHI5VFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - deployments
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
  - name: daemonset.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/daemonset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZETlNCeXBnKzV0RTZpVFpqcGNjT3VNOGQxaHBNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNekkzTVRkYUZ3MHhPVEV3TVRreE16STNNVGRhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPSjAKa3VscU54d1JpRDJxT1d4WUV5aUVoUVo1TUpOUWc5L0xUSmFaOGNFVlBlUlRtQmVObnAxeXBZWXJ5ZnhIeXVNSwpSY0JPRCtremRTZWIwWmUvcndvVkYwZmd6K3V1RXptMUwzVnR3ajRmMjNsM1I0RE9RR2JnRlRVSVExY2pRNTViCmhCVis1dGJWZnAwSXJYRFZjdHQ2a2lLcWpUN3lhUFFLS2dqdWg2akQ1b3pWUnVCMkFpMndFb28yUUY4VDJINEoKUklGVldObDVBa0dHbDZ3dmZSOHlGVXFSczBBMVExSzl1SHZOS3hQNk5HRit3QkRFLzBOMGhzM3dFZXYrNTdEMQpkZWtKOWJ3emZVOW9LM0gwVjVKMEpuamJvK2ZNeENlL1ArRHc3R3MrUGl2U3pIelhJVjgrbGVDalEyVlY4SlBKCk9NcU91ZlUyVE1FZWVIL0VvdWtDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMRDg5YnN4cXg4MDIKeHVGUlNYOUpLSXMvN3lTZnMrRnRrYVBHUzl3b3FRRmF0cFYyS3U4NVNhY1VwSG4rOVVVNmIwRXh5VDlkdzRabwpUMFJxYU5FaDZlQzIzaC9BZmh5VG5hUDVkU2kvVlVVaXFnNzlCZ0RuV0ppSHIyYkVjbTRJUEpDRE1zQWhzckl0CmRoS25udklSSmpjMCtoSVNWSnNMLzFhRXFaeis5d3AzbXhDSlF6NVVwMkgydUZVK2hDQnVUbXBMcWV6WG9VKzMKQTZEa3ZmVDdkMWZyUG9zRnJqbS9ESDFJU2FobFZleEt2bS80L25RV3p5QkpuUktyREdSVXgvOXgvaXAyY3kwWAppWGZOaVh1b0dpci9weUdyNm9IakRmdUdLby9HbzNYR3FHcEpmekp2bWJJYnJhdi9SZmFxcHliOFZrbjNyVGV0CktNbmM1RHI5VFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - daemonsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
  - name: statefulset.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/statefulset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZETlNCeXBnKzV0RTZpVFpqcGNjT3VNOGQxaHBNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNekkzTVRkYUZ3MHhPVEV3TVRreE16STNNVGRhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPSjAKa3VscU54d1JpRDJxT1d4WUV5aUVoUVo1TUpOUWc5L0xUSmFaOGNFVlBlUlRtQmVObnAxeXBZWXJ5ZnhIeXVNSwpSY0JPRCtremRTZWIwWmUvcndvVkYwZmd6K3V1RXptMUwzVnR3ajRmMjNsM1I0RE9RR2JnRlRVSVExY2pRNTViCmhCVis1dGJWZnAwSXJYRFZjdHQ2a2lLcWpUN3lhUFFLS2dqdWg2akQ1b3pWUnVCMkFpMndFb28yUUY4VDJINEoKUklGVldObDVBa0dHbDZ3dmZSOHlGVXFSczBBMVExSzl1SHZOS3hQNk5HRit3QkRFLzBOMGhzM3dFZXYrNTdEMQpkZWtKOWJ3emZVOW9LM0gwVjVKMEpuamJvK2ZNeENlL1ArRHc3R3MrUGl2U3pIelhJVjgrbGVDalEyVlY4SlBKCk9NcU91ZlUyVE1FZWVIL0VvdWtDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMRDg5YnN4cXg4MDIKeHVGUlNYOUpLSXMvN3lTZnMrRnRrYVBHUzl3b3FRRmF0cFYyS3U4NVNhY1VwSG4rOVVVNmIwRXh5VDlkdzRabwpUMFJxYU5FaDZlQzIzaC9BZmh5VG5hUDVkU2kvVlVVaXFnNzlCZ0RuV0ppSHIyYkVjbTRJUEpDRE1zQWhzckl0CmRoS25udklSSmpjMCtoSVNWSnNMLzFhRXFaeis5d3AzbXhDSlF6NVVwMkgydUZVK2hDQnVUbXBMcWV6WG9VKzMKQTZEa3ZmVDdkMWZyUG9zRnJqbS9ESDFJU2FobFZleEt2bS80L25RV3p5QkpuUktyREdSVXgvOXgvaXAyY3kwWAppWGZOaVh1b0dpci9weUdyNm9IakRmdUdLby9HbzNYR3FHcEpmekp2bWJJYnJhdi9SZmFxcHliOFZrbjNyVGV0CktNbmM1RHI5VFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - statefulsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
