---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: in-toto-webhook
  labels:
    app: in-toto-webhook
  namespace: in-toto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: in-toto-webhook
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: in-toto-webhook
          image: controlplane/in-toto-webhook:0.1-dev
          imagePullPolicy: Always
          command:
            - ./in-toto
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
            - -min-score=0
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8081
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8081
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - mountPath: /home/app/lukebond/demo-api
              name: demo-api-in-toto-layout
      volumes:
        - name: webhook-certs
          secret:
            secretName: in-toto-webhook-certs
        - name: demo-api-in-toto-layout
          configMap:
            name: in-toto-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: in-toto-webhook
  labels:
    app: in-toto-webhook
  namespace: in-toto
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: in-toto-webhook
