---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: in-toto-webhook
  labels:
    app: in-toto-webhook
    kind: validator
webhooks:
  - name: deployment.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZFais4SFZLNjRjWTJwZmh5YVYxQW1kczVTazJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNelF4TVRsYUZ3MHhPVEV3TVRreE16UXhNVGxhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOR1cKeFhIa2E4VmJCYXlRc1c4Q1RzbE9iV0xjbmd6UE5oTkhVMGN2cjE1UU45eTdOWFRXS0QrZVMvZWlBM3plenk5QgpkSEF5VDJKZGdxZGtNRk1YYzMvM251QVZxWHROdWxJcThRMUMxdFlpd05lVDk0ZDBSU0FTK0U5QXkzamNWYmMvCm9UMDdRYmlYZGhaZDQ0QmljMmphbGtFb2ZLeFpXaFVTTHN3N0VaK2lhSWpvdTFlTlcwNGJtZFZWUVdtbWFyNVIKSTBzb3FRQ3ltZ1dNR2poMEFnS0VQQ0lvSmVZbWdMd3Q0YnA5NGk0bFJTdXNkNk4xNHg0MUxsQitJQTNOaHAzegpjeVNnMEUyNGI3WVRJK3ZJVVJsbWRJYzh6YklqSjEwUzh6cERCWnhnd0o0eG9CS3AyZzhmOW9ITTNkWTVPajRhCmt2MHBXNHVPLzJmTUc1cjBRczBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZNTlBM01UTVZhWloKRzZwMVVKZ1pjc3l0UUJaSVNEaCtKbjVtQTh0Q1dYZ2ZzWGtQOFJJaytPbitMRWNZTGE0RWxTUndlVVhpSWo3NQpTYXloa0ZOSDRVQnRXZUcycnlUZ3ZXMU5sMUtEaWNCY2tUR1FGWCt0Y3hXYTNrYm9GRlh5K3NOV0NiZXBVS2E3CkcrdjF1dGJncjNIZVJJUVJ0QTZHQmw1YzNObW5URS9QckN6U21kTGhGcVplb1pTeXQrcU1zZ2FURWUrQ2orSzgKNlJTTUxEcGJRVEZXbkdoSktXYVJSYS9EOHkvYTJIMGN3VXorbSttelAwZ1BJUVR2UE4zRDB1ck1aMG9OZ1o4RgpqV09odXF4aEFsVGtZRFplT3FxTzJkS2czei9lbVJQZWFUOG90TTdldDEvYStKcHhqY0FiRVZ2ZEdTMnZJRzZ1CjQwZXB3YmlDckE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - deployments
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
  - name: daemonset.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/daemonset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZFais4SFZLNjRjWTJwZmh5YVYxQW1kczVTazJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNelF4TVRsYUZ3MHhPVEV3TVRreE16UXhNVGxhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOR1cKeFhIa2E4VmJCYXlRc1c4Q1RzbE9iV0xjbmd6UE5oTkhVMGN2cjE1UU45eTdOWFRXS0QrZVMvZWlBM3plenk5QgpkSEF5VDJKZGdxZGtNRk1YYzMvM251QVZxWHROdWxJcThRMUMxdFlpd05lVDk0ZDBSU0FTK0U5QXkzamNWYmMvCm9UMDdRYmlYZGhaZDQ0QmljMmphbGtFb2ZLeFpXaFVTTHN3N0VaK2lhSWpvdTFlTlcwNGJtZFZWUVdtbWFyNVIKSTBzb3FRQ3ltZ1dNR2poMEFnS0VQQ0lvSmVZbWdMd3Q0YnA5NGk0bFJTdXNkNk4xNHg0MUxsQitJQTNOaHAzegpjeVNnMEUyNGI3WVRJK3ZJVVJsbWRJYzh6YklqSjEwUzh6cERCWnhnd0o0eG9CS3AyZzhmOW9ITTNkWTVPajRhCmt2MHBXNHVPLzJmTUc1cjBRczBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZNTlBM01UTVZhWloKRzZwMVVKZ1pjc3l0UUJaSVNEaCtKbjVtQTh0Q1dYZ2ZzWGtQOFJJaytPbitMRWNZTGE0RWxTUndlVVhpSWo3NQpTYXloa0ZOSDRVQnRXZUcycnlUZ3ZXMU5sMUtEaWNCY2tUR1FGWCt0Y3hXYTNrYm9GRlh5K3NOV0NiZXBVS2E3CkcrdjF1dGJncjNIZVJJUVJ0QTZHQmw1YzNObW5URS9QckN6U21kTGhGcVplb1pTeXQrcU1zZ2FURWUrQ2orSzgKNlJTTUxEcGJRVEZXbkdoSktXYVJSYS9EOHkvYTJIMGN3VXorbSttelAwZ1BJUVR2UE4zRDB1ck1aMG9OZ1o4RgpqV09odXF4aEFsVGtZRFplT3FxTzJkS2czei9lbVJQZWFUOG90TTdldDEvYStKcHhqY0FiRVZ2ZEdTMnZJRzZ1CjQwZXB3YmlDckE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - daemonsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
  - name: statefulset.admission.intoto.io
    clientConfig:
      service:
        name: in-toto-webhook
        namespace: in-toto
        path: "/statefulset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZFais4SFZLNjRjWTJwZmh5YVYxQW1kczVTazJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DWXgKSkRBaUJnTlZCQU1NRzJsdUxYUnZkRzh0ZDJWaWFHOXZheTVwYmkxMGIzUnZMbk4yWXpBZUZ3MHhPREV3TVRreApNelF4TVRsYUZ3MHhPVEV3TVRreE16UXhNVGxhTUNZeEpEQWlCZ05WQkFNTUcybHVMWFJ2ZEc4dGQyVmlhRzl2CmF5NXBiaTEwYjNSdkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOR1cKeFhIa2E4VmJCYXlRc1c4Q1RzbE9iV0xjbmd6UE5oTkhVMGN2cjE1UU45eTdOWFRXS0QrZVMvZWlBM3plenk5QgpkSEF5VDJKZGdxZGtNRk1YYzMvM251QVZxWHROdWxJcThRMUMxdFlpd05lVDk0ZDBSU0FTK0U5QXkzamNWYmMvCm9UMDdRYmlYZGhaZDQ0QmljMmphbGtFb2ZLeFpXaFVTTHN3N0VaK2lhSWpvdTFlTlcwNGJtZFZWUVdtbWFyNVIKSTBzb3FRQ3ltZ1dNR2poMEFnS0VQQ0lvSmVZbWdMd3Q0YnA5NGk0bFJTdXNkNk4xNHg0MUxsQitJQTNOaHAzegpjeVNnMEUyNGI3WVRJK3ZJVVJsbWRJYzh6YklqSjEwUzh6cERCWnhnd0o0eG9CS3AyZzhmOW9ITTNkWTVPajRhCmt2MHBXNHVPLzJmTUc1cjBRczBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZNTlBM01UTVZhWloKRzZwMVVKZ1pjc3l0UUJaSVNEaCtKbjVtQTh0Q1dYZ2ZzWGtQOFJJaytPbitMRWNZTGE0RWxTUndlVVhpSWo3NQpTYXloa0ZOSDRVQnRXZUcycnlUZ3ZXMU5sMUtEaWNCY2tUR1FGWCt0Y3hXYTNrYm9GRlh5K3NOV0NiZXBVS2E3CkcrdjF1dGJncjNIZVJJUVJ0QTZHQmw1YzNObW5URS9QckN6U21kTGhGcVplb1pTeXQrcU1zZ2FURWUrQ2orSzgKNlJTTUxEcGJRVEZXbkdoSktXYVJSYS9EOHkvYTJIMGN3VXorbSttelAwZ1BJUVR2UE4zRDB1ck1aMG9OZ1o4RgpqV09odXF4aEFsVGtZRFplT3FxTzJkS2czei9lbVJQZWFUOG90TTdldDEvYStKcHhqY0FiRVZ2ZEdTMnZJRzZ1CjQwZXB3YmlDckE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
        - CREATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - statefulsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        in-toto-validation: enabled
